services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./src/Dockerfile
    dockerContext: .
    ports:
      - 8000:8000
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: PYTHONPATH
        value: /microservice
databases:
  - name: postgres-db
    plan: free
