services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./src/Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /microservice
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString

databases:
  - name: postgres-db
    plan: free