"""z

Revision ID: e88068f1af02
Revises: 9c4cdef2e285
Create Date: 2026-01-06 17:03:27.825572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88068f1af02'
down_revision: Union[str, Sequence[str], None] = '9c4cdef2e285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('api_key_id'),
    sa.UniqueConstraint('key')
    )
    op.add_column('articles', sa.Column('status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'status')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
