"""add subscriptions

Revision ID: dd669e665641
Revises: 5695d7e2cbe2
Create Date: 2025-12-05 17:04:09.508761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd669e665641'
down_revision: Union[str, Sequence[str], None] = '5695d7e2cbe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_user_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
